# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bdaf490abdef8a4af1869c197d2078eddfa3d045993e24deb607fd51f07031abbd64573d6c1ea8a62686884e97e3f445cc3ba8a2426956f04888b579b33c596

test:
  secret_key_base: c91412afc67feea4b1bfc1fd2a752d5428308af8c0626736ca033a5604030d5df84586f9516e63364ee06610cb6c84e894f07382df39e36714f0345a1b4ff705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
